import { useCallback, useState } from 'react';

interface ExportOptions {
  filename?: string;
  /** Optional title rendered as the PDF's first heading */
  title?: string;
}

/**
 * Hook to export a DOM node to a PDF.
 *
 * Strategy: html2canvas snapshot → jsPDF multi-page A4 split.
 * Both libs are loaded dynamically so they're code-split from the main bundle.
 */
export function usePdfExport() {
  const [exporting, setExporting] = useState(false);

  const exportToPdf = useCallback(
    async (node: HTMLElement | null, opts: ExportOptions = {}) => {
      if (!node) return;
      const { filename = 'github-insights.pdf', title } = opts;

      setExporting(true);
      try {
        const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
          import('html2canvas'),
          import('jspdf'),
        ]);

        // Force light styles inside the captured node — PDFs look bad with dark mode.
        const wasDark = document.documentElement.classList.contains('dark');
        if (wasDark) document.documentElement.classList.remove('dark');

        // Wait a tick so styles reflow before snapshot
        await new Promise((r) => setTimeout(r, 50));

        const canvas = await html2canvas(node, {
          scale: 2,
          backgroundColor: '#ffffff',
          useCORS: true,
          logging: false,
          windowWidth: node.scrollWidth,
        });

        if (wasDark) document.documentElement.classList.add('dark');

        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF({
          orientation: 'portrait',
          unit: 'mm',
          format: 'a4',
        });

        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const margin = 10;
        const usableWidth = pageWidth - margin * 2;
        const imgHeight = (canvas.height * usableWidth) / canvas.width;

        // Optional title
        let topOffset = margin;
        if (title) {
          pdf.setFontSize(16);
          pdf.text(title, margin, margin + 6);
          topOffset = margin + 12;
        }

        // Single-page short content
        if (imgHeight + topOffset <= pageHeight - margin) {
          pdf.addImage(imgData, 'PNG', margin, topOffset, usableWidth, imgHeight);
        } else {
          // Multi-page: slice the canvas into page-sized chunks
          const pageContentHeight = pageHeight - margin * 2;
          const pageHeightInCanvasPx = (pageContentHeight * canvas.width) / usableWidth;

          let remaining = canvas.height;
          let yOffset = 0;
          let isFirstPage = true;

          while (remaining > 0) {
            const sliceHeight = Math.min(pageHeightInCanvasPx, remaining);

            const pageCanvas = document.createElement('canvas');
            pageCanvas.width = canvas.width;
            pageCanvas.height = sliceHeight;
            const ctx = pageCanvas.getContext('2d');
            if (!ctx) break;
            ctx.fillStyle = '#ffffff';
            ctx.fillRect(0, 0, pageCanvas.width, pageCanvas.height);
            ctx.drawImage(
              canvas,
              0,
              yOffset,
              canvas.width,
              sliceHeight,
              0,
              0,
              canvas.width,
              sliceHeight
            );

            const sliceImg = pageCanvas.toDataURL('image/png');
            const sliceMmHeight = (sliceHeight * usableWidth) / canvas.width;

            if (!isFirstPage) pdf.addPage();
            pdf.addImage(sliceImg, 'PNG', margin, isFirstPage ? topOffset : margin, usableWidth, sliceMmHeight);

            yOffset += sliceHeight;
            remaining -= sliceHeight;
            isFirstPage = false;
          }
        }

        // Footer with timestamp on every page
        const totalPages = pdf.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          pdf.setFontSize(8);
          pdf.setTextColor(120);
          pdf.text(
            `Generated by GitHub Insights Pro • ${new Date().toLocaleString()} • Page ${i}/${totalPages}`,
            margin,
            pageHeight - 5
          );
        }

        pdf.save(filename);
      } finally {
        setExporting(false);
      }
    },
    []
  );

  return { exportToPdf, exporting };
}
